FROM ubuntu:18.04

RUN apt-get update && \
    apt install -y \
        gcc \
        g++ \
        cmake \
        make \
        kmod

ARG CUDA_INSTALLER
COPY $CUDA_INSTALLER /opt
RUN bash /opt/$CUDA_INSTALLER --silent --toolkit
